#Creating Tensors

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


In [2]:
if torch.cuda.is_available():
  device = torch.device("cuda")
else:
  device = torch.device("cpu")
print("Using device: ", device)

Using device:  cpu


#creating Tensors

In [4]:
a=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
a=torch.empty(2,3)
a

tensor([[2.1595e-07, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 3.8016e-39]])

In [6]:
type(a)

torch.Tensor

In [7]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.ones

<function torch._VariableFunctionsClass.ones>

In [9]:
torch.rand(2,3)

tensor([[0.7894, 0.7202, 0.3600],
        [0.0945, 0.5883, 0.7322]])

In [11]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [15]:
a=torch.tensor([[1,2,3],[3,5,6]])
a

tensor([[1, 2, 3],
        [3, 5, 6]])

In [16]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [17]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [18]:
torch.linspace(1,10,10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#Tensor Shape

In [19]:
x=torch.tensor([[1,2,3],[2,3,4]])
x

tensor([[1, 2, 3],
        [2, 3, 4]])

In [20]:
x.shape

torch.Size([2, 3])

In [21]:
torch.empty_like(x)

tensor([[          901264338,                   0,     139654182337312],
        [    139654182337312, 2314861402855339362, 2459563668847730720]])

In [22]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [24]:
torch.rand_like(x,dtype=torch.float)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [25]:
torch.tensor([1.0,2.0,3.0,4.0])

tensor([1., 2., 3., 4.])

In [26]:
x.dtype

torch.int64

In [27]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [2., 3., 4.]])

In [29]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [30]:
x-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [31]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [32]:
x*2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [33]:
x//2

tensor([[0, 1, 1],
        [2, 2, 3]])

In [34]:
x%2

tensor([[1, 0, 1],
        [0, 1, 0]])

In [36]:
a=torch.rand(2,3)
b=torch.rand(2,3)
a


tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]])

In [37]:
b

tensor([[0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]])

In [38]:
a+b

tensor([[1.0569, 0.3448, 1.2448],
        [0.7826, 0.8848, 0.8151]])

In [39]:
a-b

tensor([[-0.8462,  0.1942, -0.5272],
        [-0.3838,  0.2095, -0.8028]])

In [40]:
a*b

tensor([[0.1002, 0.0203, 0.3179],
        [0.1163, 0.1848, 0.0050]])

In [41]:
a/b

tensor([[0.1107, 3.5806, 0.4050],
        [0.3418, 1.6206, 0.0076]])

In [42]:
c=torch.tensor([-1,-2,-3])

In [43]:
torch.abs(c)

tensor([1, 2, 3])

In [45]:
torch.neg(c)

tensor([1, 2, 3])

In [46]:
d=torch.tensor([1.2,2.5,4.6])
d

tensor([1.2000, 2.5000, 4.6000])

In [47]:
torch.round(d)

tensor([1., 2., 5.])

In [48]:
torch.clamp(d,min=1,max=2)

tensor([1.2000, 2.0000, 2.0000])

In [52]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[7., 9., 7.],
        [3., 3., 4.]])

In [53]:
torch.mean(e)

tensor(5.5000)

In [54]:
torch.std(e)

tensor(2.5100)

In [55]:
torch.max(e)

tensor(9.)

In [56]:
torch.argmax(e)

tensor(1)

In [62]:
f=torch.randint(size=(1,3),low=0,high=10,dtype=torch.float32)
g=torch.randint(size=(3,1),low=0,high=10,dtype=torch.float32)

In [59]:
f

tensor([[3., 7., 0.],
        [9., 0., 9.]])

In [60]:
g

tensor([[6., 9., 5.],
        [4., 8., 8.]])

In [58]:
torch.cat((f,g),dim=0)

tensor([[3., 7., 0.],
        [9., 0., 9.],
        [6., 9., 5.],
        [4., 8., 8.]])

In [63]:
torch.matmul(f,g)

tensor([[0.]])

In [69]:
f=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
inv=torch.inverse(f)
inv
l=torch.det(f)
l

tensor(-111.)

# Special Functions

In [70]:
p=torch.tensor([10,20,30])
p

tensor([10, 20, 30])

In [72]:
torch.log(p)

tensor([2.3026, 2.9957, 3.4012])

In [73]:
torch.exp(p)

tensor([2.2026e+04, 4.8517e+08, 1.0686e+13])

In [74]:
torch.sqrt(p)

tensor([3.1623, 4.4721, 5.4772])

#sigmoid

In [75]:
torch.sigmoid(p)

tensor([1.0000, 1.0000, 1.0000])

In [78]:
#softmax
p=torch.randint(size=(1,3),low=0,high=10,dtype=torch.float32)

torch.softmax(p,dim=0)


tensor([[1., 1., 1.]])

In [79]:
torch.relu(p)

tensor([[9., 1., 8.]])

In [80]:
import torch

a = torch.tensor([1, 2, 3])
b = a.add(10)

print("a:", a)
print("b:", b)

# inline operation
a.add_(10)

print("a:", a)

a: tensor([1, 2, 3])
b: tensor([11, 12, 13])
a: tensor([11, 12, 13])


In [81]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])
c=torch.tensor
#copy
l=a.clone()

In [82]:
l

tensor([1, 2, 3])