In [2]:
import torch
torch.__version__


'2.11.0+cpu'

In [4]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
Matrix=torch.tensor([[7,8],
                     [9,10]])

In [11]:
Matrix.ndim

2

In [12]:
Matrix.shape

torch.Size([2, 2])

In [13]:
TENSOR=torch.tensor([[[1,2,3],
                      [3,6,7],
                      [2,4,5]]])

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

# random tensor

In [15]:
random_tensor=torch.rand(size=(3,4))
random_tensor,random_tensor.dtype

(tensor([[0.9661, 0.0515, 0.3167, 0.1810],
         [0.2840, 0.1145, 0.0517, 0.6517],
         [0.5780, 0.9276, 0.5537, 0.0512]]),
 torch.float32)

In [16]:
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Creating a range and tensors like

In [17]:
zeros=torch.zeros(size=(3,4))
zeros,zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [18]:
ones=torch.ones(size=(3,4))
ones,ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [20]:
zeros_to_ten=torch.arange(start=0,end=10,step=1)
zeros_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
ten_zeros=torch.zeros_like(input=zeros_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#Tensor DataType

In [24]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)

float_32_tensor.shape
float_32_tensor.dtype
float_32_tensor.device

device(type='cpu')

In [25]:
float_16_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=torch.float16)
float_16_tensor.dtype

torch.float16

#Getting information from tensor

In [27]:
some_tensor=torch.rand(3,4)

print(some_tensor)
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Shape of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.device}")

tensor([[0.9007, 0.9444, 0.9579, 0.9081],
        [0.3210, 0.2202, 0.9318, 0.0177],
        [0.2111, 0.0132, 0.3229, 0.0603]])
Shape of tensor:torch.Size([3, 4])
Shape of tensor:torch.float32
Shape of tensor:cpu


#Manipulating Tensor (tensor operations)

##basic operation

In [28]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [29]:
tensor*10

tensor([10, 20, 30])

In [30]:
tensor

tensor([1, 2, 3])

In [32]:
tensor=tensor-10
tensor


tensor([-19, -18, -17])

In [33]:
torch.multiply(tensor,10)

tensor([-190, -180, -170])

In [34]:
tensor

tensor([-19, -18, -17])

In [35]:
print(tensor,"*",tensor)
print("Equals:",tensor*tensor)

tensor([-19, -18, -17]) * tensor([-19, -18, -17])
Equals: tensor([361, 324, 289])


#Matrix multiplication

In [36]:
tensor*tensor

tensor([361, 324, 289])

In [37]:
torch.matmul(tensor,tensor)

tensor(974)

In [38]:
tensor@tensor

tensor(974)

In [39]:
%%time
value=0
for i in range(len(tensor)):
   value+=tensor[i]*tensor[i]
value

CPU times: user 450 µs, sys: 963 µs, total: 1.41 ms
Wall time: 5.07 ms


tensor(974)

In [40]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 579 µs, sys: 0 ns, total: 579 µs
Wall time: 585 µs


tensor(974)

#One of the most common errors in deep learning (shape errors)

In [43]:
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]],dtype=torch.float32)

tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]],dtype=torch.float32)

result = torch.matmul(tensor_A, tensor_B.T)

print(result)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


In [44]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [45]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [46]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [48]:
torch.manual_seed(42)
linear=torch.nn.Linear(in_features=2,out_features=6)

x=tensor_A
output=linear(x)
print(f"Input shape:{x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape:torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


#Finding the min, max, mean, sum, etc (aggregation)

In [49]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [51]:
print(f"Minimum:{x.min()}")
print(f"Miximum:{x.max()}")
print(f"Mean:{x.type(torch.float32).mean()}")
print(f"Sum:{x.sum()}")


Minimum:0
Miximum:90
Mean:45.0
Sum:450


In [52]:
torch.max(x),torch.min(x),torch.mean(x.type(torch.float32)),torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

#Positional min/max

In [55]:
tensor=torch.arange(10,100,10)
print(f"Tensor:{tensor}")

print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor:tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


#Change tensor datatype

In [56]:
tensor=torch.arange(10.,100.,10.)
tensor.dtype

torch.float32

In [57]:
tensor_float16=tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [60]:
tensor_int8=tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [61]:
import torch
x=torch.arange(1.,8.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [65]:
x_reshaped=x.reshape(1,7)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [66]:
z=x.view(1,7)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [67]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [68]:
tacked=torch.stack([x,x,x,x],dim=0)
tacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [70]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")


x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [72]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")



Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [71]:
x_orginal=torch.rand(size=(224,224,3))
x_permuted=x_orginal.permute(2,0,1)

print(f"Previous shape: {x_orginal.shape}")
print(f"Previous shape: {x_permuted.shape}")


Previous shape: torch.Size([224, 224, 3])
Previous shape: torch.Size([3, 224, 224])


#indexing

In [73]:
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [74]:
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [75]:
x[:, 0]

tensor([[1, 2, 3]])

In [76]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [77]:
x[:, 1, 1]

tensor([5])

In [78]:
x[0, 0, :]

tensor([1, 2, 3])

#PyTorch tensors & NumPy

In [79]:
import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [80]:
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [82]:
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [83]:
tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

#Reproducibility (trying to take the random out of random)

In [84]:
import torch


random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [85]:
import torch
import random

RANDOM_SEED=42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C=torch.rand(3,4)

torch.manual_seed(seed=RANDOM_SEED)
random_tensor_D=torch.rand(3,4)

print(f"random_tensor_C:\n{random_tensor_C}\n")
print(f"random_tensor_D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D


random_tensor_C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

random_tensor_D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

#Running tensors on GPUs (and making faster computations)

In [2]:
!nvidia-smi

Fri Aug 14 13:02:52 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   45C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [6]:
import torch

torch.cuda.is_available()

True

In [7]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [8]:
torch.cuda.device_count()

1

In [11]:
import torch

torch.backends.mps.is_available()

False

In [12]:
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'cpu'

In [19]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

In [15]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [17]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')